
version: "3"

services:
  django_challenge_api:
    build:
      context: .
    image: julianmesa/ieb_challenge_img:tagname
    container_name: challenge_api
    ports:
      - "8000:8000"
      
    volumes: 
      - .:/django_challenge_api
    command: sh -c "cd django_challenge_api && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    
    environment:
      - DB_HOST=db
      - DB_NAME=challenge
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    container_name: challenge_db

    environment:
      - POSTGRES_DB=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
